### ISSUE TITLE
项目名称未生效（完善所有查询与选择功能）

### ISSUE THREAD

**Issue by teacherpan** [mengyunzhi/work-home#164]
![image](https://user-images.githubusercontent.com/12424383/79034499-f322e180-7be8-11ea-93c6-fbc31ff5771b.png)

**Comment by liuyuxuan6666** [comment]
![image](https://user-images.githubusercontent.com/52695755/79457678-3505ba80-8023-11ea-8be0-81bec11d1501.png)
本地测试未发现问题，但发现查询功能有问题，因此本issue改为解决查询问题
