### ISSUE TITLE
管理员：增加把学生提权为阅卷教师的功能

### ISSUE THREAD

**Issue by liuyuxuan6666** [mengyunzhi/work-home#267]
![image](https://user-images.githubusercontent.com/52695755/83407302-057c0780-a443-11ea-91b1-e5d2e43c51e5.png)
原教师变为管理员，其他教师都为阅卷教师

**Comment by zhaokaiqiangZzz** [comment]
改增加学生为增加用户，选项多一个选择角色单选框

**Comment by liuyuxuan6666** [comment]
原有思路行不通，故关掉，重新分工
