### ISSUE TITLE
教师端：重置学生密码

### ISSUE THREAD

**Issue by zhangwenda4917** [mengyunzhi/work-home#70]

**Comment by liuyuxuan6666** [comment]
刚才看了一下，用户管理功能还差很多，学生列表都不正常。建议先把用户管理写完，重置密码就水到渠成，否则一上来就写密码重置，有点空中楼阁的感觉...

**Comment by teacherpan** [comment]
重置密码，直接在index列表中为每个学生增加一个按钮。点击按钮后重置。

**Comment by teacherpan** [comment]
![image](https://user-images.githubusercontent.com/12424383/77323847-d9604e00-6d50-11ea-82be-c2aa117ed236.png)
