### ISSUE TITLE
[BUG]第一个学生注册必报错，浏览器刷新后，后面注册的学生正常

### ISSUE THREAD

**Issue by liuyuxuan6666** [mengyunzhi/work-home#86]
![图片](https://user-images.githubusercontent.com/52695755/77495515-c732fc80-6e83-11ea-986d-e537453c2288.png)
![图片](https://user-images.githubusercontent.com/52695755/77495526-d1ed9180-6e83-11ea-9e50-235dbb5c593e.png)
![图片](https://user-images.githubusercontent.com/52695755/77495815-84bdef80-6e84-11ea-99a2-2880d7dbfa9c.png)
![图片](https://user-images.githubusercontent.com/52695755/77495879-a8813580-6e84-11ea-9152-e65e328edd17.png)

**Comment by zhangwenda4917** [comment]
本地测试未发现该问题
