### ISSUE TITLE
[BUG]学生端：答题时无法上传中文文件

### ISSUE THREAD

**Issue by liuyuxuan6666** [mengyunzhi/work-home#88]
![image](https://user-images.githubusercontent.com/52695755/77543730-0ba1b500-6ee3-11ea-81b7-ba9a3b346cde.png)
![image](https://user-images.githubusercontent.com/52695755/77543823-2e33ce00-6ee3-11ea-9c69-71a73cb98667.png)

**Comment by liyiheng1111** [comment]
本地没问题
