### ISSUE TITLE
[BUG]学生端：已上传的文件无法下载

### ISSUE THREAD

**Issue by liuyuxuan6666** [mengyunzhi/work-home#89]
![image](https://user-images.githubusercontent.com/52695755/77544214-b4501480-6ee3-11ea-9757-5b180ef04686.png)
![image](https://user-images.githubusercontent.com/52695755/77544234-bc0fb900-6ee3-11ea-8c3b-1e66710a0afb.png)

**Comment by liyiheng1111** [comment]
相关代码已修改,但未发布
